nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        components:
            schemas:
                SomeSchema:
                    type: object
                    properties:
                        foo:
                            type: string
                        bar:
                            type: integer
                    required:
                        - foo
                        - bar
                    additionalProperties: false
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
